version: '3.8'

services:
  compreface-postgres-db:
    image: postgres:11.5
    container_name: compreface-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frs
    volumes:
      - postgres-data:/var/lib/postgresql/data

  compreface-admin:
    image: exadel/compreface-admin:latest
    container_name: compreface-admin
    restart: always
    environment:
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=false
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USERNAME=
      - EMAIL_FROM=
      - EMAIL_PASSWORD=
      - ADMIN_JAVA_OPTS=-Xmx8g
    depends_on:
      - compreface-postgres-db

  compreface-api:
    image: exadel/compreface-api:latest
    container_name: compreface-api
    restart: always
    depends_on:
      - compreface-postgres-db
      - compreface-admin
    environment:
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=-Xmx8g

  compreface-fe:
    image: exadel/compreface-fe:latest
    container_name: compreface-ui
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin
    environment:
      - CLIENT_MAX_BODY_SIZE=10M
      - PROXY_READ_TIMEOUT=600s
      - PROXY_CONNECT_TIMEOUT=600s

volumes:
  postgres-data:
